name: Build Go Binaries and Prep Release
on: [push]
env:
  VERSION: "" # this gets set by set-version
jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: make set-version-${{github.run_number}}
      - run: sudo apt install xorg-dev libgl1-mesa-dev libopenal1 libopenal-dev libvorbis0a libvorbis-dev libvorbisfile3
      - run: cd ../ && git clone https://github.com/xackery/quail
      - run: go get ./...
      - run: make build-windows
      - uses: "marvinpinto/action-automatic-releases@latest"
        if: github.ref == 'refs/heads/main'
        with:
          repo_token: "${{secrets.GITHUB_TOKEN}}"
          automatic_release_tag: "${{env.VERSION}}"
          prerelease: true
          title: "${{env.VERSION}}"
          files: |
            bin/quail-view.exe